# Generated by Django 3.2.10 on 2024-04-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='syllabus',
        ),
    ]
