# Generated by Django 3.2.10 on 2024-04-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
