# Generated by Django 3.2.10 on 2024-04-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.professor', verbose_name='professor'),
        ),
    ]
