# Generated by Django 5.0.4 on 2024-04-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university_email',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=None, max_length=255, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='university_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='University Email'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('number_of_credits', models.IntegerField(default=0, verbose_name='Number of Credits')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ManyToManyField(to='management.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subject',
            },
        ),
    ]
