# Generated by Django 3.2.10 on 2024-04-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_assignment_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.assignment', verbose_name='Assignment')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'StudentAssignment',
                'verbose_name_plural': 'StudentAssignment',
                'db_table': 'StudentAssignment',
            },
        ),
    ]
