# Generated by Django 5.0.4 on 2024-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_name_professor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.ImageField(blank=True, null=True, upload_to='syllabus/', verbose_name='Syllabus'),
        ),
    ]
