# Generated by Django 3.2.10 on 2024-04-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_studentassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.assignment', verbose_name='Subject')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'SubmitAssignment',
                'verbose_name_plural': 'SubmitAssignment',
                'db_table': 'SubmitAssignment',
            },
        ),
    ]
