# Generated by Django 4.2.11 on 2024-04-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_submitassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='mediafiles/'),
        ),
    ]
