# Generated by Django 5.0.4 on 2024-04-19 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_studentsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.professor', verbose_name='Professor'),
        ),
    ]
