# Generated by Django 5.0.4 on 2024-04-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_subject_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSubject',
        ),
    ]
