# Generated by Django 5.0.4 on 2024-04-20 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_subject_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(choices=[(0, 'Semester 0'), (1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=0, verbose_name='Current Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='GPA'),
        ),
    ]
