# Generated by Django 5.0.4 on 2024-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_student_current_semester_alter_student_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='management.subject', verbose_name='Prerequisites'),
        ),
    ]
