# Generated by Django 5.0.4 on 2024-04-20 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_subject_prerequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Current Semester Subject',
                'verbose_name_plural': 'Current Semester Subjects',
            },
        ),
    ]
