# Generated by Django 5.0.4 on 2024-04-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_currentsemestersubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=0, verbose_name='Semester')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Subject History',
                'verbose_name_plural': 'Subject Histories',
            },
        ),
    ]
