# Generated by Django 5.0.4 on 2024-04-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_subjecthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSubject',
        ),
    ]
